name: Test Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arc_archs
            target: archs38-generic
            runtime_test: false

          - arch: arm_cortex-a9_vfpv3-d16
            target: mvebu-cortexa9
            runtime_test: false

          - arch: mips_24kc
            target: ath79-generic
            runtime_test: false

          - arch: mipsel_24kc
            target: mt7621
            runtime_test: false

          - arch: powerpc_464fp
            target: apm821xx-nand
            runtime_test: false

          - arch: powerpc_8540
            target: mpc85xx-p1010
            runtime_test: false

          - arch: aarch64_cortex-a53
            target: mvebu-cortexa53
            runtime_test: true

          - arch: arm_cortex-a15_neon-vfpv4
            target: armvirt-32
            runtime_test: true

          - arch: i386_pentium-mmx
            target: x86-geode
            runtime_test: true

          - arch: x86_64
            target: x86-64
            runtime_test: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: MoetaYuko/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-master
          PACKAGES: privoxy
          FEEDNAME: packages_ci
